### PR TITLE
Link Service Package with View Package via Controller Classes

### PR DESCRIPTION
**Pull request by MarouaneLoukrissi**
This pull request introduces controller classes that act as intermediaries between the classes in the service package (model) and the view package.

### CODE REVIEW

**Review by hakkm — CHANGES_REQUESTED** [review]
could you please remove the ECoin.java file and replace what you want in EnsaChain.java file, and then test if it works.

**Comment by MarouaneLoukrissi** [comment]
done

**Review by MarouaneLoukrissi — COMMENTED** [review]
done

**Review by hakkm — APPROVED** [review]
It seems good

**Pull request merged**
